# Generated by Django 4.2.5 on 2023-10-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('history', 'History'), ('english', 'English'), ('art', 'Art')], max_length=20),
        ),
    ]
