# Generated by Django 4.2.5 on 2023-10-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_schoolclass_schoolclassuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staff', 'staff'), ('teatcher', 'teatcher'), ('student', 'student')], default='staff', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='year_number',
            field=models.CharField(choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4'), ('5', 'Year 5'), ('6', 'Year 6'), ('7', 'Year 7'), ('8', 'Year 8'), ('9', 'Year 9'), ('10', 'Year 10'), ('11', 'Year 11'), ('12', 'Year 12')], max_length=15),
        ),
    ]
